---
name: WWW-PastebinCa-Create
version: 0.001
author:
  - 'Zoffix Znet <zoffix@cpan.org>'
abstract: create new pastes on http://pastebin.ca from Perl
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.04
  Class::Data::Accessor: 0.04001
  URI: 1.35
  WWW::Mechanize: 1.34
build_requires:
  Test::More: 0
provides:
  WWW::PastebinCa::Create:
    file: lib/WWW/PastebinCa/Create.pm
    version: 0.001
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
